FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN chmod +x /app/docker/start-api.sh

EXPOSE 8000
CMD ["/app/docker/start-api.sh"]
