"""BM25 retrieval over trusted, project-generated local artifacts."""

from __future__ import annotations

import logging
import math
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import numpy as np

from processing.bm25_indexer import BM25Indexer

from .models import RetrievalResult

logger = logging.getLogger(__name__)


class SparseRetriever:
    """Load and query the BM25 artifact produced by ``BM25Indexer``.

    Pickle deserialization can execute arbitrary code. Only pass trusted local
    artifacts generated by this project; never download and load arbitrary files.
    Metadata filters are applied to all scored positions before top-k selection.
    """

    def __init__(self, index_path: str | Path, default_top_k: int = 10) -> None:
        if not isinstance(default_top_k, int) or default_top_k <= 0:
            raise ValueError("default_top_k must be a positive integer")
        self.index_path = Path(index_path)
        self.default_top_k = default_top_k
        self.indexer: BM25Indexer | None = None
        self.bm25: Any | None = None
        self.documents: list[list[str]] = []
        self.chunks: list[dict[str, Any]] = []
        self.preprocessing_config: dict[str, Any] = {}
        self.version: str | None = None
        self.created_at: str | None = None
        self.load()

    def load(self) -> None:
        """Deserialize and validate a trusted local BM25 index."""

        if not self.index_path.is_file():
            raise FileNotFoundError(f"BM25 index not found: {self.index_path}")
        try:
            indexer = BM25Indexer.load(self.index_path)
        except Exception as exc:
            raise ValueError(
                f"Could not load BM25 index {self.index_path}: {exc}"
            ) from exc
        if indexer.index is None or not indexer.chunks:
            raise ValueError(f"BM25 index is empty: {self.index_path}")
        if len(indexer.documents) != len(indexer.chunks):
            raise ValueError("BM25 corpus and chunk mapping lengths differ")
        for position, chunk in enumerate(indexer.chunks):
            if not isinstance(chunk, Mapping):
                raise ValueError(
                    f"Chunk mapping at position {position} is not a mapping"
                )
            if not str(chunk.get("chunk_id", "")).strip():
                raise ValueError(
                    f"Chunk mapping at position {position} is missing chunk_id"
                )
            if not str(chunk.get("text", "")).strip():
                raise ValueError(
                    f"Chunk mapping at position {position} is missing text"
                )
        self.indexer = indexer
        self.bm25 = indexer.index
        self.documents = indexer.documents
        self.chunks = [dict(chunk) for chunk in indexer.chunks]
        self.preprocessing_config = dict(indexer.preprocessing_config)
        self.version = indexer.version
        self.created_at = indexer.created_at

    def search(
        self,
        query: str | list[str],
        top_k: int | None = None,
        filters: dict[str, Any] | None = None,
        score_threshold: float | None = None,
    ) -> list[RetrievalResult]:
        """Return raw BM25 scores mapped back to complete chunk records."""

        if self.bm25 is None or self.indexer is None:
            raise RuntimeError("BM25 index is not loaded")
        limit = self.default_top_k if top_k is None else top_k
        if not isinstance(limit, int) or isinstance(limit, bool) or limit <= 0:
            raise ValueError("top_k must be a positive integer")
        if isinstance(query, str):
            tokens = self.indexer.tokenize(query, self.preprocessing_config)
        elif isinstance(query, list):
            if any(not isinstance(token, str) for token in query):
                raise TypeError("query token lists may contain only strings")
            tokens = [token for token in query if token]
        else:
            raise TypeError("query must be a string or list of string tokens")
        if not tokens:
            raise ValueError("query must contain at least one sparse token")
        if score_threshold is not None and not math.isfinite(float(score_threshold)):
            raise ValueError("score_threshold must be finite")
        _validate_filters(filters)

        scores = np.asarray(self.bm25.get_scores(tokens), dtype=float)
        if scores.ndim != 1 or len(scores) != len(self.chunks):
            raise ValueError("BM25 score count does not match the chunk mapping")
        candidate_indices = np.asarray(
            [
                index
                for index, chunk in enumerate(self.chunks)
                if np.isfinite(scores[index])
                and (score_threshold is None or scores[index] >= score_threshold)
                and _matches_filters(chunk, filters)
            ],
            dtype=int,
        )
        if not candidate_indices.size:
            return []

        result_count = min(limit, candidate_indices.size)
        if result_count < candidate_indices.size:
            candidate_scores = scores[candidate_indices]
            selected = np.argpartition(candidate_scores, -result_count)[-result_count:]
            ranked = candidate_indices[selected]
        else:
            ranked = candidate_indices
        ranked = sorted(ranked.tolist(), key=lambda index: (-scores[index], index))

        return [
            RetrievalResult.from_payload(
                self.chunks[index], score=float(scores[index]), source="sparse"
            )
            for index in ranked[:limit]
        ]

    def health_check(self) -> dict[str, Any]:
        """Return corpus/mapping integrity information without reloading the file."""

        document_count = len(self.documents)
        mapping_count = len(self.chunks)
        return {
            "loaded": self.bm25 is not None,
            "index_path": str(self.index_path),
            "document_count": document_count,
            "chunk_mapping_count": mapping_count,
            "metadata_count": sum(
                isinstance(chunk.get("metadata"), Mapping) for chunk in self.chunks
            ),
            "mapping_valid": bool(document_count) and document_count == mapping_count,
            "preprocessing_config": dict(self.preprocessing_config),
            "version": self.version,
            "created_at": self.created_at,
        }


def _validate_filters(filters: dict[str, Any] | None) -> None:
    if filters is None:
        return
    if not isinstance(filters, dict):
        raise TypeError("filters must be a dictionary")
    for key, expected in filters.items():
        if not isinstance(key, str) or not key.strip():
            raise ValueError("filter field names must be non-empty strings")
        if isinstance(expected, Mapping) and (
            not expected or not set(expected).issubset({"gt", "gte", "lt", "lte"})
        ):
            raise ValueError(f"Invalid range filter for {key!r}")


def _matches_filters(chunk: Mapping[str, Any], filters: dict[str, Any] | None) -> bool:
    if not filters:
        return True
    metadata = chunk.get("metadata")
    nested = metadata if isinstance(metadata, Mapping) else {}
    for key, expected in filters.items():
        actual = chunk.get(key, nested.get(key))
        if isinstance(expected, Mapping):
            comparisons = {
                "gt": lambda: actual > expected["gt"],
                "gte": lambda: actual >= expected["gte"],
                "lt": lambda: actual < expected["lt"],
                "lte": lambda: actual <= expected["lte"],
            }
            try:
                if not all(comparisons[name]() for name in expected):
                    return False
            except TypeError:
                return False
        elif isinstance(expected, (list, tuple, set)):
            if actual not in expected:
                return False
        elif actual != expected:
            return False
    return True
